//! Cloud provider and IaC CLIs.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "aws" => Some(AWS),
        "gcloud" => Some(GCLOUD),
        "az" => Some(AZ),
        "doctl" => Some(DOCTL),
        "flyctl" | "fly" => Some(FLY),
        "heroku" => Some(HEROKU),
        "vercel" => Some(VERCEL),
        "netlify" => Some(NETLIFY),
        "wrangler" => Some(WRANGLER),
        "supabase" => Some(SUPABASE),
        "firebase" => Some(FIREBASE),
        "pulumi" => Some(PULUMI),
        "terraform" => Some(TERRAFORM),
        "tofu" => Some(TOFU),
        "sam" => Some(SAM),
        "serverless" | "sls" => Some(SERVERLESS),
        "cdk" => Some(CDK),
        "ansible" => Some(ANSIBLE),
        "ansible-galaxy" => Some(ANSIBLE_GALAXY),
        "vagrant" => Some(VAGRANT),
        "packer" => Some(PACKER),
        "vault" => Some(VAULT),
        "consul" => Some(CONSUL),
        "nomad" => Some(NOMAD),
        _ => None,
    }
}

const AWS: &[&str] = &[
    "accessanalyzer",
    "acm",
    "apigateway",
    "apigatewayv2",
    "application-autoscaling",
    "autoscaling",
    "backup",
    "batch",
    "cloudformation",
    "cloudfront",
    "cloudtrail",
    "cloudwatch",
    "codebuild",
    "codecommit",
    "codedeploy",
    "codepipeline",
    "cognito-idp",
    "configure",
    "dynamodb",
    "ec2",
    "ecr",
    "ecs",
    "efs",
    "eks",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "emr",
    "events",
    "firehose",
    "glue",
    "help",
    "iam",
    "kinesis",
    "kms",
    "lambda",
    "logs",
    "organizations",
    "rds",
    "redshift",
    "route53",
    "s3",
    "s3api",
    "secretsmanager",
    "ses",
    "sns",
    "sqs",
    "ssm",
    "sts",
    "wafv2",
];

const GCLOUD: &[&str] = &[
    "ai",
    "app",
    "auth",
    "builds",
    "components",
    "compute",
    "config",
    "container",
    "dataflow",
    "dataproc",
    "deploy",
    "dns",
    "domains",
    "endpoints",
    "filestore",
    "firestore",
    "functions",
    "help",
    "iam",
    "info",
    "init",
    "kms",
    "logging",
    "monitoring",
    "projects",
    "pubsub",
    "run",
    "secrets",
    "services",
    "source",
    "spanner",
    "sql",
    "storage",
    "topic",
    "version",
];

const AZ: &[&str] = &[
    "account",
    "acr",
    "acs",
    "ad",
    "advisor",
    "aks",
    "appconfig",
    "appservice",
    "backup",
    "batch",
    "bicep",
    "cdn",
    "cloud",
    "cognitiveservices",
    "configure",
    "consumption",
    "container",
    "cosmosdb",
    "deployment",
    "disk",
    "dns",
    "eventgrid",
    "eventhubs",
    "extension",
    "feature",
    "functionapp",
    "group",
    "hdinsight",
    "identity",
    "image",
    "iot",
    "keyvault",
    "lab",
    "lock",
    "login",
    "logout",
    "managedapp",
    "monitor",
    "mysql",
    "netappfiles",
    "network",
    "policy",
    "postgres",
    "redis",
    "resource",
    "role",
    "search",
    "security",
    "servicebus",
    "signalr",
    "snapshot",
    "sql",
    "storage",
    "tag",
    "term",
    "version",
    "vm",
    "vmss",
    "webapp",
];

const DOCTL: &[&str] = &[
    "1-click",
    "account",
    "apps",
    "auth",
    "balance",
    "billing-history",
    "compute",
    "databases",
    "genai",
    "invoices",
    "kubernetes",
    "monitoring",
    "projects",
    "registry",
    "serverless",
    "spaces",
    "version",
    "vpcs",
];

const FLY: &[&str] = &[
    "apps",
    "auth",
    "certs",
    "checks",
    "completions",
    "config",
    "console",
    "deploy",
    "destroy",
    "docs",
    "doctor",
    "history",
    "image",
    "ips",
    "logs",
    "machine",
    "orgs",
    "platform",
    "proxy",
    "regions",
    "releases",
    "scale",
    "secrets",
    "ssh",
    "status",
    "volumes",
    "wireguard",
];

const HEROKU: &[&str] = &[
    "addons",
    "apps",
    "auth",
    "buildpacks",
    "certs",
    "ci",
    "config",
    "container",
    "domains",
    "drains",
    "features",
    "git",
    "help",
    "keys",
    "labs",
    "local",
    "logs",
    "maintenance",
    "members",
    "notifications",
    "orgs",
    "pg",
    "pipelines",
    "plugins",
    "ps",
    "redis",
    "regions",
    "releases",
    "run",
    "stack",
    "status",
    "teams",
    "update",
    "webhooks",
];

const VERCEL: &[&str] = &[
    "alias", "bisect", "build", "certs", "deploy", "dev", "dns", "domains", "env", "git", "help",
    "init", "inspect", "link", "list", "login", "logout", "logs", "project", "promote", "pull",
    "redeploy", "remove", "rollback", "switch", "teams", "whoami",
];

const NETLIFY: &[&str] = &[
    "addons",
    "api",
    "build",
    "completion",
    "deploy",
    "dev",
    "env",
    "functions",
    "init",
    "link",
    "login",
    "logout",
    "open",
    "sites",
    "status",
    "switch",
    "unlink",
    "watch",
];

const WRANGLER: &[&str] = &[
    "auth", "deploy", "dev", "docs", "init", "kv", "pages", "publish", "r2", "secret", "tail",
    "types", "version", "whoami",
];

const SUPABASE: &[&str] = &[
    "completion",
    "db",
    "functions",
    "gen",
    "init",
    "link",
    "login",
    "logout",
    "migration",
    "projects",
    "secrets",
    "start",
    "status",
    "stop",
    "test",
];

const FIREBASE: &[&str] = &[
    "apps",
    "auth",
    "crashlytics",
    "database",
    "deploy",
    "emulators",
    "experiments",
    "ext",
    "firestore",
    "functions",
    "help",
    "hosting",
    "init",
    "login",
    "logout",
    "open",
    "projects",
    "remoteconfig",
    "serve",
    "setup",
    "target",
    "use",
];

const PULUMI: &[&str] = &[
    "about",
    "cancel",
    "config",
    "console",
    "destroy",
    "gen-completion",
    "help",
    "import",
    "login",
    "logout",
    "logs",
    "new",
    "org",
    "plugin",
    "policy",
    "preview",
    "refresh",
    "stack",
    "state",
    "up",
    "update",
    "version",
    "watch",
    "whoami",
];

const TERRAFORM: &[&str] = &[
    "apply",
    "console",
    "destroy",
    "env",
    "fmt",
    "force-unlock",
    "get",
    "graph",
    "import",
    "init",
    "login",
    "logout",
    "output",
    "plan",
    "providers",
    "refresh",
    "show",
    "state",
    "taint",
    "test",
    "untaint",
    "validate",
    "version",
    "workspace",
];

const TOFU: &[&str] = &[
    "apply",
    "console",
    "destroy",
    "fmt",
    "force-unlock",
    "get",
    "graph",
    "import",
    "init",
    "login",
    "logout",
    "output",
    "plan",
    "providers",
    "refresh",
    "show",
    "state",
    "taint",
    "test",
    "untaint",
    "validate",
    "version",
    "workspace",
];

const SAM: &[&str] = &[
    "build", "delete", "deploy", "init", "list", "local", "logs", "package", "pipeline", "publish",
    "remote", "sync", "traces", "validate",
];

const SERVERLESS: &[&str] = &[
    "config", "create", "deploy", "info", "install", "invoke", "logs", "metrics", "offline",
    "package", "plugin", "print", "remove", "rollback", "slstats",
];

const CDK: &[&str] = &[
    "ack",
    "bootstrap",
    "context",
    "deploy",
    "destroy",
    "diff",
    "docs",
    "doctor",
    "init",
    "list",
    "metadata",
    "synth",
    "watch",
];

const ANSIBLE: &[&str] = &[
    "all",
    "config",
    "console",
    "doc",
    "galaxy",
    "inventory",
    "playbook",
    "pull",
    "vault",
];

const ANSIBLE_GALAXY: &[&str] = &[
    "collection",
    "role",
    "search",
    "info",
    "install",
    "list",
    "remove",
];

const VAGRANT: &[&str] = &[
    "box",
    "cloud",
    "destroy",
    "global-status",
    "halt",
    "help",
    "init",
    "package",
    "plugin",
    "port",
    "powershell",
    "provision",
    "push",
    "rdp",
    "reload",
    "resume",
    "share",
    "snapshot",
    "ssh",
    "ssh-config",
    "status",
    "suspend",
    "up",
    "upload",
    "validate",
    "version",
    "winrm",
];

const PACKER: &[&str] = &[
    "build",
    "console",
    "fix",
    "hcl2_upgrade",
    "init",
    "inspect",
    "plugins",
    "validate",
    "version",
];

const VAULT: &[&str] = &[
    "agent",
    "audit",
    "auth",
    "debug",
    "delete",
    "kv",
    "lease",
    "list",
    "login",
    "namespace",
    "operator",
    "path-help",
    "policy",
    "print",
    "read",
    "secrets",
    "server",
    "ssh",
    "status",
    "token",
    "unwrap",
    "version",
    "write",
];

const CONSUL: &[&str] = &[
    "acl",
    "agent",
    "catalog",
    "config",
    "connect",
    "debug",
    "event",
    "exec",
    "force-leave",
    "info",
    "intention",
    "join",
    "keygen",
    "keyring",
    "kv",
    "leave",
    "lock",
    "login",
    "logout",
    "maint",
    "members",
    "monitor",
    "operator",
    "peering",
    "reload",
    "services",
    "snapshot",
    "tls",
    "validate",
    "version",
    "watch",
];

const NOMAD: &[&str] = &[
    "acl",
    "agent",
    "alloc",
    "deployment",
    "eval",
    "job",
    "namespace",
    "node",
    "operator",
    "quota",
    "recommendation",
    "scaling",
    "sentinel",
    "server",
    "service",
    "status",
    "system",
    "ui",
    "var",
    "version",
    "volume",
];
