//! Container engine CLIs.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "docker" => Some(DOCKER),
        "podman" => Some(PODMAN),
        "nerdctl" => Some(NERDCTL),
        "buildah" => Some(BUILDAH),
        "skopeo" => Some(SKOPEO),
        "containerd" => Some(CONTAINERD),
        "ctr" => Some(CTR),
        "cosign" => Some(COSIGN),
        "crane" => Some(CRANE),
        "trivy" => Some(TRIVY),
        _ => None,
    }
}

const DOCKER: &[&str] = &[
    "attach",
    "build",
    "builder",
    "commit",
    "compose",
    "config",
    "container",
    "context",
    "cp",
    "create",
    "diff",
    "events",
    "exec",
    "export",
    "history",
    "image",
    "images",
    "import",
    "info",
    "inspect",
    "kill",
    "load",
    "login",
    "logout",
    "logs",
    "network",
    "pause",
    "port",
    "ps",
    "pull",
    "push",
    "rename",
    "restart",
    "rm",
    "rmi",
    "run",
    "save",
    "search",
    "start",
    "stats",
    "stop",
    "system",
    "tag",
    "top",
    "unpause",
    "update",
    "version",
    "volume",
    "wait",
];

const PODMAN: &[&str] = &[
    "attach",
    "build",
    "commit",
    "container",
    "cp",
    "create",
    "diff",
    "exec",
    "export",
    "generate",
    "healthcheck",
    "history",
    "image",
    "images",
    "import",
    "info",
    "init",
    "inspect",
    "kill",
    "load",
    "login",
    "logout",
    "logs",
    "machine",
    "manifest",
    "network",
    "pause",
    "pod",
    "port",
    "ps",
    "pull",
    "push",
    "rename",
    "restart",
    "rm",
    "rmi",
    "run",
    "save",
    "search",
    "secret",
    "start",
    "stats",
    "stop",
    "system",
    "tag",
    "top",
    "unpause",
    "volume",
    "wait",
];

const NERDCTL: &[&str] = &[
    "build",
    "commit",
    "compose",
    "container",
    "cp",
    "create",
    "exec",
    "images",
    "info",
    "inspect",
    "kill",
    "load",
    "login",
    "logout",
    "logs",
    "namespace",
    "network",
    "pause",
    "ps",
    "pull",
    "push",
    "restart",
    "rm",
    "rmi",
    "run",
    "save",
    "start",
    "stats",
    "stop",
    "system",
    "tag",
    "top",
    "unpause",
    "volume",
    "wait",
];

const BUILDAH: &[&str] = &[
    "add",
    "bud",
    "commit",
    "config",
    "containers",
    "copy",
    "from",
    "images",
    "info",
    "inspect",
    "mount",
    "pull",
    "push",
    "rm",
    "rmi",
    "run",
    "tag",
    "umount",
    "unshare",
    "version",
];

const SKOPEO: &[&str] = &[
    "copy",
    "delete",
    "inspect",
    "list-tags",
    "login",
    "logout",
    "manifest",
    "sync",
];

const CONTAINERD: &[&str] = &["config", "plugin", "publish", "help"];

const CTR: &[&str] = &[
    "containers",
    "content",
    "events",
    "images",
    "info",
    "namespaces",
    "plugins",
    "pprof",
    "run",
    "snapshots",
    "tasks",
    "version",
];

const COSIGN: &[&str] = &[
    "attach",
    "attest",
    "clean",
    "copy",
    "dockerfile",
    "download",
    "generate",
    "generate-key-pair",
    "initialize",
    "load",
    "login",
    "manifest",
    "public-key",
    "save",
    "sign",
    "sign-blob",
    "tree",
    "triangulate",
    "verify",
    "verify-attestation",
    "verify-blob",
    "version",
];

const CRANE: &[&str] = &[
    "append", "auth", "blob", "catalog", "config", "copy", "delete", "digest", "export", "flatten",
    "index", "manifest", "mutate", "pull", "push", "rebase", "tag", "validate", "version",
];

const TRIVY: &[&str] = &[
    "clean",
    "config",
    "convert",
    "filesystem",
    "image",
    "kubernetes",
    "module",
    "plugin",
    "repo",
    "rootfs",
    "sbom",
    "server",
    "version",
    "vm",
];
