//! Database and datastore CLIs.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "psql" => Some(PSQL),
        "mysql" => Some(MYSQL),
        "sqlite3" => Some(SQLITE),
        "redis-cli" => Some(REDIS),
        "mongosh" => Some(MONGOSH),
        "mongo" => Some(MONGO),
        "etcdctl" => Some(ETCDCTL),
        "rabbitmqctl" => Some(RABBITMQCTL),
        "kafka-topics.sh" | "kafka-topics" => Some(KAFKA_TOPICS),
        "mc" => Some(MC),
        "rclone" => Some(RCLONE),
        "restic" => Some(RESTIC),
        "borg" => Some(BORG),
        _ => None,
    }
}

const PSQL: &[&str] = &[
    "-c",
    "-d",
    "-f",
    "-h",
    "-l",
    "-p",
    "-U",
    "-W",
    "-w",
    "-X",
    "--help",
    "--version",
];

const MYSQL: &[&str] = &[
    "-e",
    "-h",
    "-p",
    "-P",
    "-u",
    "-D",
    "--help",
    "--version",
    "--execute",
];

const SQLITE: &[&str] = &[
    ".help", ".tables", ".schema", ".quit", ".mode", ".headers", ".dump",
];

const REDIS: &[&str] = &[
    "AUTH",
    "GET",
    "SET",
    "DEL",
    "EXISTS",
    "EXPIRE",
    "KEYS",
    "SCAN",
    "HGET",
    "HSET",
    "HGETALL",
    "LPUSH",
    "RPUSH",
    "LPOP",
    "RPOP",
    "LRANGE",
    "SADD",
    "SMEMBERS",
    "ZADD",
    "ZRANGE",
    "PUBLISH",
    "SUBSCRIBE",
    "INFO",
    "PING",
    "FLUSHDB",
    "FLUSHALL",
    "CONFIG",
    "CLIENT",
    "CLUSTER",
    "MEMORY",
    "MONITOR",
    "SLOWLOG",
    "TTL",
    "TYPE",
    "INCR",
    "DECR",
    "APPEND",
    "STRLEN",
];

const MONGOSH: &[&str] = &[
    "help", "show", "use", "db", "exit", "quit", "load", "it", "JSON", "BSON",
];

const MONGO: &[&str] = &["help", "show", "use", "exit", "quit"];

const ETCDCTL: &[&str] = &[
    "alarm",
    "auth",
    "check",
    "compaction",
    "defrag",
    "del",
    "elect",
    "endpoint",
    "get",
    "lease",
    "lock",
    "make-mirror",
    "member",
    "migrate",
    "move-leader",
    "put",
    "role",
    "snapshot",
    "txn",
    "user",
    "version",
    "watch",
];

const RABBITMQCTL: &[&str] = &[
    "add_user",
    "add_vhost",
    "change_password",
    "clear_password",
    "clear_permissions",
    "close_all_connections",
    "close_connection",
    "delete_user",
    "delete_vhost",
    "environment",
    "eval",
    "force_boot",
    "list_bindings",
    "list_channels",
    "list_connections",
    "list_consumers",
    "list_exchanges",
    "list_permissions",
    "list_queues",
    "list_unresponsive_queues",
    "list_user_permissions",
    "list_users",
    "list_vhosts",
    "node_health_check",
    "report",
    "reset",
    "rotate_logs",
    "set_permissions",
    "set_policy",
    "set_user_tags",
    "set_vhost_limits",
    "shutdown",
    "start_app",
    "status",
    "stop",
    "stop_app",
    "wait",
];

const KAFKA_TOPICS: &[&str] = &[
    "--bootstrap-server",
    "--create",
    "--delete",
    "--describe",
    "--list",
    "--alter",
    "--topic",
];

const MC: &[&str] = &[
    "admin",
    "alias",
    "anonymous",
    "cat",
    "cp",
    "diff",
    "du",
    "encrypt",
    "event",
    "find",
    "get",
    "head",
    "help",
    "ilm",
    "ls",
    "mb",
    "mirror",
    "mv",
    "od",
    "pipe",
    "quota",
    "rb",
    "replicate",
    "retention",
    "rm",
    "share",
    "sql",
    "stat",
    "support",
    "tag",
    "tree",
    "undo",
    "update",
    "version",
    "watch",
];

const RCLONE: &[&str] = &[
    "about",
    "authorize",
    "backend",
    "bisync",
    "cat",
    "check",
    "checksum",
    "cleanup",
    "completion",
    "config",
    "copy",
    "copyto",
    "copyurl",
    "cryptcheck",
    "cryptdecode",
    "dedupe",
    "delete",
    "deletefile",
    "genautocomplete",
    "gendocs",
    "hashsum",
    "help",
    "link",
    "listremotes",
    "ls",
    "lsd",
    "lsf",
    "lsjson",
    "lsl",
    "md5sum",
    "mkdir",
    "mount",
    "move",
    "moveto",
    "ncdu",
    "obscure",
    "purge",
    "rcat",
    "rcd",
    "rmdir",
    "rmdirs",
    "selfupdate",
    "serve",
    "settier",
    "sha1sum",
    "size",
    "sync",
    "test",
    "touch",
    "tree",
    "version",
];

const RESTIC: &[&str] = &[
    "backup",
    "cache",
    "cat",
    "check",
    "copy",
    "diff",
    "dump",
    "find",
    "forget",
    "generate",
    "init",
    "key",
    "list",
    "ls",
    "migrate",
    "mount",
    "prune",
    "recover",
    "repair",
    "restore",
    "rewrite",
    "snapshots",
    "stats",
    "tag",
    "unlock",
    "version",
];

const BORG: &[&str] = &[
    "benchmark",
    "break-lock",
    "check",
    "compact",
    "config",
    "create",
    "delete",
    "diff",
    "export-tar",
    "extract",
    "info",
    "init",
    "key",
    "list",
    "mount",
    "prune",
    "rename",
    "serve",
    "umount",
    "upgrade",
    "with-lock",
];
