//! Kubernetes and cluster tooling.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "kubectl" => Some(KUBECTL),
        "helm" => Some(HELM),
        "minikube" => Some(MINIKUBE),
        "kind" => Some(KIND),
        "k3d" => Some(K3D),
        "kustomize" => Some(KUSTOMIZE),
        "eksctl" => Some(EKSCTL),
        "istioctl" => Some(ISTIOCTL),
        "linkerd" => Some(LINKERD),
        "argocd" => Some(ARGOCD),
        "flux" => Some(FLUX),
        "k9s" => Some(K9S),
        _ => None,
    }
}

const KUBECTL: &[&str] = &[
    "annotate",
    "api-resources",
    "api-versions",
    "apply",
    "attach",
    "auth",
    "autoscale",
    "certificate",
    "cluster-info",
    "completion",
    "config",
    "cordon",
    "cp",
    "create",
    "delete",
    "describe",
    "diff",
    "drain",
    "edit",
    "exec",
    "explain",
    "expose",
    "get",
    "kustomize",
    "label",
    "logs",
    "patch",
    "plugin",
    "port-forward",
    "proxy",
    "replace",
    "rollout",
    "run",
    "scale",
    "set",
    "taint",
    "top",
    "uncordon",
    "version",
    "wait",
];

const HELM: &[&str] = &[
    "completion",
    "create",
    "dependency",
    "env",
    "get",
    "help",
    "history",
    "install",
    "lint",
    "list",
    "package",
    "plugin",
    "pull",
    "push",
    "registry",
    "repo",
    "rollback",
    "search",
    "show",
    "status",
    "template",
    "test",
    "uninstall",
    "upgrade",
    "verify",
    "version",
];

const MINIKUBE: &[&str] = &[
    "addons",
    "completion",
    "config",
    "cp",
    "dashboard",
    "delete",
    "docker-env",
    "image",
    "ip",
    "logs",
    "mount",
    "node",
    "pause",
    "podman-env",
    "profile",
    "service",
    "ssh",
    "start",
    "status",
    "stop",
    "tunnel",
    "unpause",
    "update-check",
    "version",
];

const KIND: &[&str] = &[
    "build",
    "completion",
    "create",
    "delete",
    "export",
    "get",
    "load",
    "version",
];

const K3D: &[&str] = &[
    "cluster",
    "completion",
    "config",
    "image",
    "kubeconfig",
    "node",
    "registry",
    "version",
];

const KUSTOMIZE: &[&str] = &[
    "build",
    "cfg",
    "completion",
    "create",
    "edit",
    "localize",
    "version",
];

const EKSCTL: &[&str] = &[
    "completion",
    "create",
    "delete",
    "drain",
    "enable",
    "get",
    "scale",
    "set",
    "unset",
    "update",
    "upgrade",
    "utils",
    "version",
];

const ISTIOCTL: &[&str] = &[
    "analyze",
    "authz",
    "bug-report",
    "completion",
    "dashboard",
    "install",
    "kube-inject",
    "proxy-config",
    "proxy-status",
    "uninstall",
    "upgrade",
    "validate",
    "version",
    "wait",
    "waypoint",
    "ztunnel-config",
];

const LINKERD: &[&str] = &[
    "check",
    "completion",
    "diagnostics",
    "identity",
    "install",
    "jaeger",
    "multicluster",
    "profile",
    "uninject",
    "upgrade",
    "version",
    "viz",
];

const ARGOCD: &[&str] = &[
    "account",
    "admin",
    "app",
    "cert",
    "cluster",
    "completion",
    "context",
    "gpg",
    "login",
    "logout",
    "proj",
    "repo",
    "version",
];

const FLUX: &[&str] = &[
    "bootstrap",
    "check",
    "completion",
    "create",
    "delete",
    "export",
    "get",
    "install",
    "logs",
    "reconcile",
    "resume",
    "suspend",
    "uninstall",
    "version",
];

const K9S: &[&str] = &["info", "version"];
