//! Language toolchains and package managers.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "cargo" => Some(CARGO),
        "rustup" => Some(RUSTUP),
        "go" => Some(GO),
        "npm" => Some(NPM),
        "yarn" => Some(YARN),
        "pnpm" => Some(PNPM),
        "bun" => Some(BUN),
        "deno" => Some(DENO),
        "pip" | "pip3" => Some(PIP),
        "pipx" => Some(PIPX),
        "uv" => Some(UV),
        "poetry" => Some(POETRY),
        "gem" => Some(GEM),
        "bundle" => Some(BUNDLE),
        "composer" => Some(COMPOSER),
        "mix" => Some(MIX),
        "flutter" => Some(FLUTTER),
        "dart" => Some(DART),
        "dotnet" => Some(DOTNET),
        _ => None,
    }
}

const CARGO: &[&str] = &[
    "add",
    "bench",
    "build",
    "check",
    "clean",
    "clippy",
    "doc",
    "fmt",
    "generate-lockfile",
    "help",
    "init",
    "install",
    "login",
    "logout",
    "metadata",
    "new",
    "owner",
    "package",
    "pkgid",
    "publish",
    "remove",
    "report",
    "run",
    "rustc",
    "rustdoc",
    "search",
    "test",
    "tree",
    "uninstall",
    "update",
    "vendor",
    "verify-project",
    "version",
    "yank",
];

const RUSTUP: &[&str] = &[
    "check",
    "default",
    "doc",
    "man",
    "show",
    "update",
    "toolchain",
    "target",
    "component",
    "override",
    "run",
    "which",
    "help",
    "self",
    "set",
];

const GO: &[&str] = &[
    "bug", "build", "clean", "doc", "env", "fix", "fmt", "generate", "get", "help", "install",
    "list", "mod", "work", "run", "test", "tool", "version", "vet",
];

const NPM: &[&str] = &[
    "access",
    "adduser",
    "audit",
    "bin",
    "bugs",
    "cache",
    "ci",
    "completion",
    "config",
    "dedupe",
    "deprecate",
    "diff",
    "dist-tag",
    "docs",
    "doctor",
    "edit",
    "exec",
    "explain",
    "explore",
    "fund",
    "help",
    "init",
    "install",
    "link",
    "ll",
    "login",
    "logout",
    "ls",
    "outdated",
    "owner",
    "pack",
    "ping",
    "pkg",
    "prefix",
    "profile",
    "prune",
    "publish",
    "query",
    "rebuild",
    "repo",
    "restart",
    "root",
    "run",
    "run-script",
    "search",
    "set",
    "shrinkwrap",
    "star",
    "stars",
    "start",
    "stop",
    "team",
    "test",
    "token",
    "uninstall",
    "unpublish",
    "unstar",
    "update",
    "version",
    "view",
    "whoami",
];

const YARN: &[&str] = &[
    "add",
    "bin",
    "cache",
    "config",
    "create",
    "dedupe",
    "dlx",
    "exec",
    "explain",
    "info",
    "init",
    "install",
    "link",
    "npm",
    "pack",
    "plugin",
    "remove",
    "run",
    "set",
    "up",
    "why",
    "workspace",
    "workspaces",
];

const PNPM: &[&str] = &[
    "add", "audit", "bin", "config", "dedupe", "dlx", "exec", "init", "install", "link", "list",
    "outdated", "pack", "publish", "rebuild", "remove", "run", "store", "test", "update", "why",
];

const BUN: &[&str] = &[
    "add", "build", "create", "init", "install", "link", "pm", "remove", "run", "test", "update",
    "upgrade", "x",
];

const DENO: &[&str] = &[
    "add",
    "bench",
    "bundle",
    "cache",
    "check",
    "compile",
    "completions",
    "coverage",
    "doc",
    "eval",
    "fmt",
    "info",
    "init",
    "install",
    "jupyter",
    "lint",
    "lsp",
    "publish",
    "repl",
    "run",
    "serve",
    "task",
    "test",
    "types",
    "uninstall",
    "upgrade",
    "vendor",
];

const PIP: &[&str] = &[
    "cache",
    "check",
    "config",
    "debug",
    "download",
    "freeze",
    "hash",
    "help",
    "install",
    "list",
    "show",
    "uninstall",
    "wheel",
];

const PIPX: &[&str] = &[
    "ensurepath",
    "environment",
    "inject",
    "install",
    "list",
    "reinstall",
    "run",
    "runpip",
    "uninstall",
    "upgrade",
    "upgrade-all",
];

const UV: &[&str] = &[
    "add", "build", "cache", "export", "help", "init", "lock", "pip", "python", "remove", "run",
    "sync", "tool", "tree", "version", "venv",
];

const POETRY: &[&str] = &[
    "add", "build", "check", "config", "env", "export", "init", "install", "lock", "new",
    "publish", "remove", "run", "shell", "show", "update", "version",
];

const GEM: &[&str] = &[
    "build",
    "cert",
    "check",
    "cleanup",
    "contents",
    "dependency",
    "environment",
    "fetch",
    "generate_index",
    "help",
    "info",
    "install",
    "list",
    "lock",
    "open",
    "outdated",
    "owner",
    "pristine",
    "push",
    "query",
    "rdoc",
    "search",
    "server",
    "sources",
    "specification",
    "stale",
    "uninstall",
    "unpack",
    "update",
    "which",
    "yank",
];

const BUNDLE: &[&str] = &[
    "add", "binstubs", "cache", "check", "clean", "config", "console", "doctor", "exec", "help",
    "info", "init", "inject", "install", "list", "lock", "open", "outdated", "platform", "plugin",
    "pristine", "remove", "show", "update", "viz",
];

const COMPOSER: &[&str] = &[
    "about",
    "archive",
    "browse",
    "bump",
    "check-platform-reqs",
    "clear-cache",
    "config",
    "create-project",
    "depends",
    "diagnose",
    "dump-autoload",
    "exec",
    "fund",
    "global",
    "help",
    "init",
    "install",
    "licenses",
    "list",
    "outdated",
    "prohibits",
    "reinstall",
    "remove",
    "require",
    "run-script",
    "search",
    "self-update",
    "show",
    "status",
    "suggests",
    "update",
    "validate",
    "why",
    "why-not",
];

const MIX: &[&str] = &[
    "app.config",
    "app.start",
    "app.tree",
    "archive.build",
    "archive.install",
    "archive.uninstall",
    "clean",
    "cmd",
    "compile",
    "deps.clean",
    "deps.compile",
    "deps.get",
    "deps.tree",
    "deps.unlock",
    "deps.update",
    "do",
    "escript.build",
    "format",
    "help",
    "hex",
    "iex",
    "local",
    "new",
    "phx.new",
    "profile.cprof",
    "profile.eprof",
    "profile.fprof",
    "release",
    "run",
    "test",
    "xref",
];

const FLUTTER: &[&str] = &[
    "analyze",
    "assemble",
    "attach",
    "bash-completion",
    "build",
    "channel",
    "clean",
    "config",
    "create",
    "custom-devices",
    "devices",
    "doctor",
    "downgrade",
    "drive",
    "emulators",
    "gen-l10n",
    "install",
    "logs",
    "precache",
    "pub",
    "run",
    "screenshot",
    "symbolize",
    "test",
    "upgrade",
];

const DART: &[&str] = &[
    "analyze", "compile", "create", "devtools", "doc", "fix", "format", "info", "pub", "run",
    "test",
];

const DOTNET: &[&str] = &[
    "add",
    "build",
    "build-server",
    "clean",
    "format",
    "help",
    "list",
    "msbuild",
    "new",
    "nuget",
    "pack",
    "publish",
    "remove",
    "restore",
    "run",
    "sln",
    "store",
    "test",
    "tool",
    "watch",
    "workload",
];
