//! OS package managers, service managers, and session tools.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "brew" => Some(BREW),
        "apt" => Some(APT),
        "apt-get" => Some(APT_GET),
        "dnf" => Some(DNF),
        "yum" => Some(YUM),
        "pacman" => Some(PACMAN),
        "yay" | "paru" => Some(AUR),
        "zypper" => Some(ZYPPER),
        "apk" => Some(APK),
        "flatpak" => Some(FLATPAK),
        "snap" => Some(SNAP),
        "nix" => Some(NIX),
        "systemctl" => Some(SYSTEMCTL),
        "launchctl" => Some(LAUNCHCTL),
        "tmux" => Some(TMUX),
        "zellij" => Some(ZELLIJ),
        "screen" => Some(SCREEN),
        "loginctl" => Some(LOGINCTL),
        "hostnamectl" => Some(HOSTNAMECTL),
        "timedatectl" => Some(TIMEDATECTL),
        "networkctl" => Some(NETWORKCTL),
        "resolvectl" => Some(RESOLVECTL),
        "virsh" => Some(VIRSH),
        "multipass" => Some(MULTIPASS),
        "lima" => Some(LIMA),
        "colima" => Some(COLIMA),
        _ => None,
    }
}

const BREW: &[&str] = &[
    "analytics",
    "autoremove",
    "cask",
    "cleanup",
    "commands",
    "config",
    "deps",
    "desc",
    "doctor",
    "fetch",
    "formula",
    "gist-logs",
    "home",
    "info",
    "install",
    "leaves",
    "link",
    "list",
    "log",
    "migrate",
    "missing",
    "options",
    "outdated",
    "pin",
    "postinstall",
    "reinstall",
    "search",
    "services",
    "tap",
    "uninstall",
    "unlink",
    "unpin",
    "untap",
    "update",
    "upgrade",
    "uses",
];

const APT: &[&str] = &[
    "autoclean",
    "autoremove",
    "build-dep",
    "changelog",
    "depends",
    "download",
    "edit-sources",
    "full-upgrade",
    "help",
    "install",
    "list",
    "moo",
    "policy",
    "purge",
    "reinstall",
    "remove",
    "search",
    "show",
    "source",
    "update",
    "upgrade",
];

const APT_GET: &[&str] = &[
    "autoclean",
    "autoremove",
    "build-dep",
    "check",
    "clean",
    "dist-upgrade",
    "download",
    "dselect-upgrade",
    "install",
    "purge",
    "remove",
    "source",
    "update",
    "upgrade",
];

const DNF: &[&str] = &[
    "autoremove",
    "check",
    "check-update",
    "clean",
    "distro-sync",
    "downgrade",
    "group",
    "help",
    "history",
    "info",
    "install",
    "list",
    "makecache",
    "mark",
    "module",
    "provides",
    "reinstall",
    "remove",
    "repolist",
    "repoquery",
    "search",
    "shell",
    "swap",
    "updateinfo",
    "upgrade",
];

const YUM: &[&str] = &[
    "check-update",
    "clean",
    "deplist",
    "groupinfo",
    "groupinstall",
    "grouplist",
    "groupremove",
    "info",
    "install",
    "list",
    "makecache",
    "provides",
    "reinstall",
    "remove",
    "repolist",
    "search",
    "update",
    "upgrade",
];

const PACMAN: &[&str] = &[
    "-D", "-F", "-Q", "-R", "-S", "-T", "-U", // often used as ops; also word forms below
    "database", "files", "query", "remove", "sync", "deptest", "upgrade",
];

const AUR: &[&str] = &[
    "build",
    "clean",
    "deptest",
    "download",
    "getpkgbuild",
    "query",
    "remove",
    "show",
    "sync",
    "upgrade",
    "version",
];

const ZYPPER: &[&str] = &[
    "addrepo",
    "clean",
    "dist-upgrade",
    "download",
    "info",
    "install",
    "list-patches",
    "list-updates",
    "modifyrepo",
    "patch",
    "patch-check",
    "ps",
    "refresh",
    "remove",
    "removerepo",
    "repos",
    "search",
    "se",
    "source-install",
    "update",
    "verify",
];

const APK: &[&str] = &[
    "add", "audit", "cache", "del", "dot", "fetch", "fix", "index", "info", "list", "manifest",
    "policy", "stats", "update", "upgrade", "version",
];

const FLATPAK: &[&str] = &[
    "build",
    "build-bundle",
    "build-commit-from",
    "build-export",
    "build-finish",
    "build-import-bundle",
    "build-init",
    "build-sign",
    "build-update-repo",
    "config",
    "create-usb",
    "document-export",
    "document-info",
    "document-list",
    "document-unexport",
    "enter",
    "history",
    "info",
    "install",
    "kill",
    "list",
    "mask",
    "override",
    "permission-list",
    "permission-remove",
    "permission-reset",
    "permission-set",
    "permission-show",
    "ps",
    "remote-add",
    "remote-delete",
    "remote-info",
    "remote-list",
    "remote-ls",
    "remote-modify",
    "repair",
    "run",
    "search",
    "uninstall",
    "update",
];

const SNAP: &[&str] = &[
    "abort",
    "ack",
    "alias",
    "aliases",
    "auto-import",
    "changes",
    "check-snapshot",
    "connect",
    "connections",
    "create-cohort",
    "debug",
    "disable",
    "disconnect",
    "download",
    "enable",
    "find",
    "forget",
    "get",
    "help",
    "info",
    "install",
    "interface",
    "interfaces",
    "known",
    "list",
    "login",
    "logout",
    "managed",
    "okay",
    "pack",
    "prefer",
    "prepare-image",
    "refresh",
    "remove",
    "restore",
    "revert",
    "run",
    "save",
    "saved",
    "services",
    "set",
    "start",
    "stop",
    "switch",
    "tasks",
    "unalias",
    "unset",
    "version",
    "wait",
    "watch",
    "whoami",
];

const NIX: &[&str] = &[
    "build",
    "develop",
    "edit",
    "eval",
    "flake",
    "fmt",
    "hash",
    "help",
    "key",
    "log",
    "nar",
    "path-info",
    "profile",
    "realisation",
    "registry",
    "repl",
    "run",
    "search",
    "shell",
    "store",
    "why-depends",
];

const SYSTEMCTL: &[&str] = &[
    "cat",
    "daemon-reload",
    "daemon-reexec",
    "default",
    "disable",
    "edit",
    "emergency",
    "enable",
    "get-default",
    "halt",
    "help",
    "hibernate",
    "hybrid-sleep",
    "is-active",
    "is-enabled",
    "is-failed",
    "is-system-running",
    "kexec",
    "kill",
    "link",
    "list-dependencies",
    "list-jobs",
    "list-sockets",
    "list-timers",
    "list-unit-files",
    "list-units",
    "mask",
    "poweroff",
    "preset",
    "reenable",
    "reload",
    "reload-or-restart",
    "rescue",
    "reset-failed",
    "restart",
    "revert",
    "set-default",
    "set-property",
    "show",
    "show-environment",
    "start",
    "status",
    "stop",
    "suspend",
    "try-reload-or-restart",
    "try-restart",
    "unmask",
];

const LAUNCHCTL: &[&str] = &[
    "bootstrap",
    "bootout",
    "enable",
    "disable",
    "kickstart",
    "kill",
    "blame",
    "print",
    "procinfo",
    "hostinfo",
    "list",
    "error",
    "load",
    "unload",
    "start",
    "stop",
    "remove",
    "submit",
    "limit",
];

const TMUX: &[&str] = &[
    "attach",
    "attach-session",
    "bind-key",
    "break-pane",
    "capture-pane",
    "choose-client",
    "choose-session",
    "choose-tree",
    "choose-window",
    "clear-history",
    "clock-mode",
    "command-prompt",
    "confirm-before",
    "copy-mode",
    "delete-buffer",
    "detach-client",
    "display-message",
    "display-panes",
    "find-window",
    "has-session",
    "if-shell",
    "join-pane",
    "kill-pane",
    "kill-server",
    "kill-session",
    "kill-window",
    "last-pane",
    "last-window",
    "link-window",
    "list-buffers",
    "list-clients",
    "list-commands",
    "list-keys",
    "list-panes",
    "list-sessions",
    "list-windows",
    "load-buffer",
    "lock-client",
    "lock-server",
    "lock-session",
    "move-pane",
    "move-window",
    "new-session",
    "new-window",
    "next-layout",
    "next-window",
    "paste-buffer",
    "pipe-pane",
    "previous-layout",
    "previous-window",
    "refresh-client",
    "rename-session",
    "rename-window",
    "resize-pane",
    "resize-window",
    "respawn-pane",
    "respawn-window",
    "rotate-window",
    "run-shell",
    "save-buffer",
    "select-layout",
    "select-pane",
    "select-window",
    "send-keys",
    "send-prefix",
    "server-info",
    "set-buffer",
    "set-environment",
    "set-option",
    "set-window-option",
    "show-buffer",
    "show-environment",
    "show-messages",
    "show-options",
    "show-window-options",
    "source-file",
    "split-window",
    "start-server",
    "suspend-client",
    "swap-pane",
    "swap-window",
    "switch-client",
    "unbind-key",
    "unlink-window",
    "wait-for",
];

const ZELLIJ: &[&str] = &[
    "action",
    "attach",
    "convert-config",
    "convert-layout",
    "convert-theme",
    "delete-session",
    "edit",
    "help",
    "kill-all-sessions",
    "kill-session",
    "list-sessions",
    "options",
    "plugin",
    "run",
    "setup",
];

const SCREEN: &[&str] = &["-S", "-r", "-R", "-d", "-ls", "-x", "-wipe"];

const LOGINCTL: &[&str] = &[
    "activate",
    "enable-linger",
    "disable-linger",
    "kill-session",
    "kill-user",
    "list-sessions",
    "list-users",
    "lock-session",
    "lock-sessions",
    "show-session",
    "show-user",
    "terminate-session",
    "terminate-user",
    "unlock-session",
    "user-status",
];

const HOSTNAMECTL: &[&str] = &[
    "status",
    "hostname",
    "icon-name",
    "chassis",
    "deployment",
    "location",
];

const TIMEDATECTL: &[&str] = &[
    "status",
    "show",
    "set-time",
    "set-timezone",
    "list-timezones",
    "set-local-rtc",
    "set-ntp",
    "timesync-status",
    "show-timesync",
];

const NETWORKCTL: &[&str] = &[
    "list",
    "status",
    "lldp",
    "label",
    "delete",
    "up",
    "down",
    "renew",
    "forcerenew",
    "reconfigure",
    "reload",
    "edit",
    "cat",
];

const RESOLVECTL: &[&str] = &[
    "query",
    "service",
    "openpgp",
    "tlsa",
    "status",
    "statistics",
    "reset-statistics",
    "flush-caches",
    "reset-server-features",
    "dns",
    "domain",
    "default-route",
    "llmnr",
    "mdns",
    "dnssec",
    "dnsovertls",
    "nta",
    "revert",
];

const VIRSH: &[&str] = &[
    "attach-device",
    "autostart",
    "capabilities",
    "connect",
    "console",
    "create",
    "define",
    "destroy",
    "detach-device",
    "dominfo",
    "domstate",
    "dumpxml",
    "edit",
    "help",
    "list",
    "net-define",
    "net-list",
    "net-start",
    "reboot",
    "reset",
    "restore",
    "resume",
    "save",
    "shutdown",
    "snapshot-create",
    "snapshot-list",
    "start",
    "suspend",
    "undefine",
    "version",
    "vncdisplay",
];

const MULTIPASS: &[&str] = &[
    "alias", "aliases", "delete", "exec", "find", "get", "help", "info", "launch", "list", "mount",
    "networks", "purge", "recover", "restart", "set", "shell", "start", "stop", "suspend",
    "transfer", "umount", "unalias", "version",
];

const LIMA: &[&str] = &[
    "completion",
    "copy",
    "create",
    "delete",
    "disk",
    "edit",
    "factory-reset",
    "list",
    "shell",
    "snapshot",
    "start",
    "stop",
    "sudoers",
    "template",
    "validate",
];

const COLIMA: &[&str] = &[
    "completion",
    "delete",
    "kubernetes",
    "list",
    "nvm",
    "ssh",
    "start",
    "status",
    "stop",
    "template",
    "version",
];
