//! VCS and forge CLIs.

pub(super) fn names(cmd: &str) -> Option<&'static [&'static str]> {
    match cmd {
        "git" => Some(GIT),
        "jj" => Some(JJ),
        "hg" => Some(HG),
        "svn" => Some(SVN),
        "fossil" => Some(FOSSIL),
        "gh" => Some(GH),
        "glab" => Some(GLAB),
        "hub" => Some(HUB),
        _ => None,
    }
}

const GIT: &[&str] = &[
    "add",
    "am",
    "annotate",
    "apply",
    "archive",
    "bisect",
    "blame",
    "branch",
    "checkout",
    "cherry",
    "cherry-pick",
    "clean",
    "clone",
    "commit",
    "config",
    "describe",
    "diff",
    "fetch",
    "gc",
    "grep",
    "init",
    "log",
    "ls-files",
    "merge",
    "mv",
    "pull",
    "push",
    "rebase",
    "reflog",
    "remote",
    "reset",
    "restore",
    "revert",
    "rm",
    "shortlog",
    "show",
    "stash",
    "status",
    "submodule",
    "switch",
    "tag",
    "worktree",
];

const JJ: &[&str] = &[
    "abandon",
    "absorb",
    "bookmark",
    "commit",
    "config",
    "describe",
    "diff",
    "edit",
    "git",
    "init",
    "log",
    "new",
    "next",
    "prev",
    "rebase",
    "resolve",
    "restore",
    "show",
    "simplify-parents",
    "space",
    "split",
    "squash",
    "status",
    "undo",
    "version",
];

const HG: &[&str] = &[
    "add",
    "annotate",
    "archive",
    "backout",
    "bisect",
    "bookmarks",
    "branch",
    "branches",
    "bundle",
    "cat",
    "clone",
    "commit",
    "config",
    "copy",
    "diff",
    "export",
    "forget",
    "grep",
    "heads",
    "help",
    "identify",
    "import",
    "incoming",
    "init",
    "log",
    "manifest",
    "merge",
    "outgoing",
    "paths",
    "pull",
    "push",
    "remove",
    "rename",
    "resolve",
    "revert",
    "root",
    "serve",
    "status",
    "summary",
    "tag",
    "tags",
    "unbundle",
    "update",
    "verify",
];

const SVN: &[&str] = &[
    "add",
    "blame",
    "cat",
    "changelist",
    "checkout",
    "cleanup",
    "commit",
    "copy",
    "delete",
    "diff",
    "export",
    "help",
    "import",
    "info",
    "list",
    "lock",
    "log",
    "merge",
    "mkdir",
    "move",
    "patch",
    "propdel",
    "propedit",
    "propget",
    "proplist",
    "propset",
    "relocate",
    "resolve",
    "resolved",
    "revert",
    "status",
    "switch",
    "unlock",
    "update",
];

const FOSSIL: &[&str] = &[
    "add", "amend", "bisect", "branch", "cat", "changes", "checkout", "clean", "clone", "close",
    "commit", "diff", "extras", "finfo", "help", "info", "init", "ls", "merge", "mv", "open",
    "pull", "push", "rebuild", "remote", "revert", "rm", "settings", "stash", "status", "sync",
    "tag", "timeline", "ui", "undo", "update", "version",
];

const GH: &[&str] = &[
    "alias",
    "api",
    "auth",
    "browse",
    "cache",
    "codespace",
    "completion",
    "config",
    "extension",
    "gist",
    "gpg-key",
    "issue",
    "label",
    "org",
    "pr",
    "project",
    "release",
    "repo",
    "ruleset",
    "run",
    "search",
    "secret",
    "ssh-key",
    "status",
    "variable",
    "workflow",
];

const GLAB: &[&str] = &[
    "alias",
    "api",
    "auth",
    "changelog",
    "check-update",
    "ci",
    "cluster",
    "completion",
    "config",
    "duo",
    "incident",
    "issue",
    "job",
    "label",
    "mr",
    "release",
    "repo",
    "schedule",
    "snippet",
    "ssh-key",
    "user",
    "variable",
    "version",
];

const HUB: &[&str] = &[
    "api",
    "browse",
    "ci-status",
    "clone",
    "compare",
    "create",
    "delete",
    "fork",
    "help",
    "issue",
    "pr",
    "pull-request",
    "release",
    "sync",
];
